### ISSUE TITLE
Question for the dataset.py

### ISSUE THREAD

**Issue by halbielee** [janghyuncho/PiCIE#7]
Hello, thanks for sharing your excellent work!

I have a question about your code, especially _coco_train_dataset.py_.

https://github.com/janghyuncho/PiCIE/blob/62d274897990f9c980cf1000464628a25d22e45b/data/coco_train_dataset.py#L97-L106
When applying the _transform_tensor_ function to the image, it applies to the variable _image_ not _image1_.

Is there any issue for this?

Thanks!

**Comment by janghyuncho** [comment]
Hi halbielee, 

Thank you for your interest in our work! I am happy to help you. 

Indeed, you are absolutely correct that it appears to be a bug on our end. The code for the result from the paper did not have this bug (only during refactoring). However, we did try this version before and it makes very small difference; in fact, many contrastive learning papers choose this way (contrasting between x <-> T(x) instead of T1(x) <-> T2(x)). 

I fixed the code just now. 

Thank you!

Jang Hyun Cho

**Comment by janghyuncho** [comment]
Hi halbielee,

Here is the training [log](https://github.com/janghyuncho/PiCIE/blob/master/logs/picie_with_updated_code.out) of PiCIE with the updated code. 

Best,

Jang Hyun Cho

**Comment by halbielee** [comment]
Thank you for the quick and kind reply :)

**Comment by ShunZuo-AI** [comment]
> Hi halbielee,
> 
> Here is the training [log](https://github.com/janghyuncho/PiCIE/blob/master/logs/picie_with_updated_code.out) of PiCIE with the updated code.
> 
> ACC - All: 51.5297 mIOU - All: 14.7917 ACC - Thing: 76.6696 mIOU - Thing: 18.1085 ACC - Stuff: 64.4714 mIOU - Stuff: 26.3870
> 
> Best,
> 
> Jang Hyun Cho
hello,this is a great work,I don't find these files   COCO_2017_train.json and COCO_2017_val.json in COCO datasets,I need your help
